<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="hoang-ngoc-anh" failures="4" tests="14" name="TestSuite.ChangePassword" time="123.120" errors="0" timestamp="2022-12-29T23:56:58 ICT" skipped="0">
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_08" time="10.759"/>
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_07" time="7.738">
    <failure message="By.xpath: //div[contains(@class,&#039;alert-message-error&#039;)][1]//pis not visible did not expect to find [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: By.xpath: //div[contains(@class,'alert-message-error')][1]//pis not visible did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at Common.Utilities.assertTextValueVisible(Utilities.java:401)
at CommonScreen.ChangePasswordScreen.changePassword(ChangePasswordScreen.java:48)
at TestSuite.ChangePassword.MODULE6_07(ChangePassword.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MODULE6_07 -->
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_02" time="2.504"/>
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_06" time="2.306"/>
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_09" time="10.715"/>
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_10" time="7.828">
    <failure message="By.xpath: //div[contains(@class,&#039;alert-message-error&#039;)][1]//pis not visible did not expect to find [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: By.xpath: //div[contains(@class,'alert-message-error')][1]//pis not visible did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at Common.Utilities.assertTextValueVisible(Utilities.java:401)
at CommonScreen.ChangePasswordScreen.changePassword(ChangePasswordScreen.java:48)
at TestSuite.ChangePassword.MODULE6_10(ChangePassword.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MODULE6_10 -->
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_05" time="2.622"/>
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_01" time="21.852"/>
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_11" time="2.205">
    <failure message="Value is not correct: Expected: &quot;Mật khẩu phải có độ dài từ 8 đến 20 ký tự&quot;; Actual: &quot;Mật khẩu cần tối thiểu 8 kí tự&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Mật khẩu phải có độ dài từ 8 đến 20 ký tự"; Actual: "Mật khẩu cần tối thiểu 8 kí tự"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:455)
at Common.Utilities.assertTextValue(Utilities.java:390)
at Common.Utilities.assertTextValueVisible(Utilities.java:402)
at CommonScreen.ChangePasswordScreen.changePassword(ChangePasswordScreen.java:51)
at TestSuite.ChangePassword.MODULE6_11(ChangePassword.java:83)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MODULE6_11 -->
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_03" time="2.189"/>
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_12" time="21.333"/>
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_14" time="7.839">
    <failure message="By.xpath: //div[contains(@class,&#039;alert-message-error&#039;)][2]//pis not visible did not expect to find [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: By.xpath: //div[contains(@class,'alert-message-error')][2]//pis not visible did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at Common.Utilities.assertTextValueVisible(Utilities.java:401)
at CommonScreen.ChangePasswordScreen.changePassword(ChangePasswordScreen.java:51)
at TestSuite.ChangePassword.MODULE6_14(ChangePassword.java:100)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MODULE6_14 -->
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_04" time="2.298"/>
  <testcase classname="TestSuite.ChangePassword" name="MODULE6_13" time="20.932"/>
</testsuite> <!-- TestSuite.ChangePassword -->
