<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="anhhn-HP-EliteBook-8470p" failures="1" tests="16" name="TestSuite.Contact" time="89.551" errors="0" timestamp="2022-11-07T01:03:14 ICT" skipped="0">
  <testcase classname="TestSuite.Contact" name="MODULE1_15" time="1.887">
    <failure message="Value is not correct: Expected: &quot;test@gmail.com&quot;; Actual: &quot; test@gmail.com &quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "test@gmail.com"; Actual: " test@gmail.com "
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:455)
at Common.Utilities.assertInputValue(Utilities.java:420)
at Common.Utilities.inputValueAndValidate(Utilities.java:302)
at CommonScreen.ContactScreen.contact(ContactScreen.java:53)
at TestSuite.Contact.MODULE1_15(Contact.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MODULE1_15 -->
  <testcase classname="TestSuite.Contact" name="MODULE1_03" time="5.090"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_07" time="5.129"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_16" time="5.052"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_14" time="5.047"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_05" time="5.065"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_13" time="5.012"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_12" time="4.961"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_06" time="4.907"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_01" time="9.061"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_02" time="5.319"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_09" time="5.098"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_10" time="8.852"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_08" time="5.004"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_04" time="9.002"/>
  <testcase classname="TestSuite.Contact" name="MODULE1_11" time="5.065"/>
</testsuite> <!-- TestSuite.Contact -->
