<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="hoang-ngoc-anh" failures="4" tests="8" name="TestSuite.Register" time="19.579" errors="0" timestamp="2022-12-29T21:30:17 ICT" skipped="0">
  <testcase classname="TestSuite.Register" name="MODULE4_03" time="2.626">
    <failure message="Value is not correct: Expected: &quot;Cảm ơn bạn đã đăng ký nhận thông báo&quot;; Actual: &quot;Cảm ơn bạn đã đăng kí nhận thông tin từ Medica!&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Cảm ơn bạn đã đăng ký nhận thông báo"; Actual: "Cảm ơn bạn đã đăng kí nhận thông tin từ Medica!"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:455)
at Common.Utilities.assertTextValue(Utilities.java:390)
at Common.Utilities.assertTextValueVisible(Utilities.java:402)
at CommonScreen.HomeScreen.register(HomeScreen.java:63)
at TestSuite.Register.MODULE4_03(Register.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MODULE4_03 -->
  <testcase classname="TestSuite.Register" name="MODULE4_04" time="2.377"/>
  <testcase classname="TestSuite.Register" name="MODULE4_06" time="2.945"/>
  <testcase classname="TestSuite.Register" name="MODULE4_02" time="2.377">
    <failure message="Value is not correct: Expected: &quot;Cảm ơn bạn đã đăng ký nhận thông báo&quot;; Actual: &quot;Cảm ơn bạn đã đăng kí nhận thông tin từ Medica!&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Cảm ơn bạn đã đăng ký nhận thông báo"; Actual: "Cảm ơn bạn đã đăng kí nhận thông tin từ Medica!"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:455)
at Common.Utilities.assertTextValue(Utilities.java:390)
at Common.Utilities.assertTextValueVisible(Utilities.java:402)
at CommonScreen.HomeScreen.register(HomeScreen.java:63)
at TestSuite.Register.MODULE4_02(Register.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MODULE4_02 -->
  <testcase classname="TestSuite.Register" name="MODULE4_05" time="2.379"/>
  <testcase classname="TestSuite.Register" name="MODULE4_01" time="2.401">
    <failure message="Value is not correct: Expected: &quot;Vui lòng nhập email của bạn&quot;; Actual: &quot;Email không đúng định dạng!&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Vui lòng nhập email của bạn"; Actual: "Email không đúng định dạng!"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:455)
at Common.Utilities.assertTextValue(Utilities.java:390)
at Common.Utilities.assertTextValueVisible(Utilities.java:402)
at CommonScreen.HomeScreen.register(HomeScreen.java:63)
at TestSuite.Register.MODULE4_01(Register.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MODULE4_01 -->
  <testcase classname="TestSuite.Register" name="MODULE4_07" time="2.547"/>
  <testcase classname="TestSuite.Register" name="MODULE4_08" time="1.927">
    <failure message="Value is not correct: Expected: &quot;test@gmail.com&quot;; Actual: &quot;  test@gmail.com   &quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "test@gmail.com"; Actual: "  test@gmail.com   "
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:455)
at Common.Utilities.assertInputValue(Utilities.java:420)
at Common.Utilities.inputValueAndValidate(Utilities.java:302)
at CommonScreen.HomeScreen.register(HomeScreen.java:60)
at TestSuite.Register.MODULE4_08(Register.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MODULE4_08 -->
</testsuite> <!-- TestSuite.Register -->
